## **<span style= "color:green;"><center>Pandas</center> </span>**

## ***<span style= "color:purple;">Imports</span>***

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# how to create simple series
list_1 = ['a','b','c','d']
labels = [1,2,3,4]
ser_1 = pd.Series(data=list_1, index=labels)
ser_1

# how to convert array to series
arr_1 = np.array([1,2,3,4])
ser_2 = pd.Series(arr_1)
ser_2

# how to convert dic to series
dic_1 = {
    'f_name' : 'sheraz',
    'l_name' : 'ahmed',
    'age' : 25
} 
ser_3 = pd.Series(dic_1, name='personal info')
ser_3

In [ ]:
ser_1[1]
ser_2[0]
ser_3['f_name']

In [ ]:
ser_2 + ser_2

In [ ]:
np.exp(ser_2)

### ***DataFrames***

In [2]:
arr_2 = np.random.randint(10,50, size=(2,3))
arr_2

array([[31, 43, 18],
       [26, 44, 11]])

In [9]:
# array , row and column
df = pd.DataFrame(arr_2, index= ['A','B'],columns=['C','D','E'])

In [11]:
df

C   D   E
A  31  43  18
B  26  44  11

In [12]:
# creating dataFrame with multiple series
# arr = np.arange(1,5, dtype= float)
# indi = np.array(['a','b','c','d'])

# dict_3 = {
#     'One' : pd.Series(arr, index=indi),
#     'Two' : pd.Series(arr, index=indi)
# }
# df = pd.DataFrame(dict_3)

In [13]:
df

C   D   E
A  31  43  18
B  26  44  11

### ***Editing and retrieving data***

In [17]:
# getting data with dataframe 
df[['C']]
df[['C','D']]

C   D
A  31  43
B  26  44

In [15]:
#  row as a Series
df.loc['A']


C    31
D    43
E    18
Name: A, dtype: int32

In [16]:
# with index position
df.iloc[1]

C    26
D    44
E    11
Name: B, dtype: int32

In [20]:
df

C   D   E
A  31  43  18
B  26  44  11

In [21]:
# add another column 
df['total'] = df['D']+df['E']
df

C   D   E  total
A  31  43  18     61
B  26  44  11     55

In [22]:
new_arr_1 = np.random.randint(10,50, size=(2,3))
new_arr_1

array([[10, 45, 16],
       [37, 42, 28]])

In [36]:
# create a DF with data, row labels and column labels 

new_df = pd.DataFrame(new_arr_1, index= ['A','B'], columns=['C','D','E'])
new_df

C   D   E
A  10  45  16
B  37  42  28

In [40]:
# # get a column
# new_df['C']

# #get multiple columns
# new_df[['C','E']]

# # #get a row as series
# new_df.loc['A']

# #get row by index position
# new_df.iloc[1]

# # #get cell with row and column
# new_df.loc['A','C']

# # #make a new column
# new_df['total'] = new_df['C'] + new_df['D'] + new_df['E']
# new_df

#make a new row by appending 
new_row = pd.DataFrame({
    'C' : [44],
    'D' : [45],
    'E' : [46]
})
new_df = pd.concat([new_df,new_row], ignore_index=True)

new_df

# # new_row = pd.Series(dic_1, name='F')
# # new_df = pd.concat([new_df,new_row],ignore_index=True)
# new_row
# #delete a column

# new_df

level_0  index   C   D   E
0      0.0    0.0  10  45  16
1      1.0    1.0  37  42  28
2      2.0    2.0  44  45  46
3      3.0    3.0  44  45  46
4      4.0    NaN  44  45  46
5      NaN    NaN  44  45  46

In [25]:
new_row2 = pd.DataFrame({
    'C' : [44],
    'D' : [45],
    'E' : [46]
})
df = pd.concat([df,new_row2], ignore_index=True)
df

C   D   E  total
0  31  43  18   61.0
1  26  44  11   55.0
2  44  45  46    NaN

In [32]:
new_df

C   D   E
0  10  45  16
1  37  42  28
2  44  45  46
3  44  45  46
4  44  45  46

In [34]:
#delete a column
# df.drop('total', axis=1, inplace=True)
# df
#delete a row
new_df.drop([2,3,4],axis=0, inplace=True)
# #delete a multiple rows
# new_df.drop([4,5,6,10,11,12,13,14], axis=0)

In [43]:
df

C   D   E
0  31  43  18
1  26  44  11
2  44  45  46

In [44]:
df.drop([2], axis=0, inplace=True)

In [45]:
df['sex'] = ['Men', 'Women']
df.set_index('sex', inplace=True)

In [46]:
df

C   D   E
sex              
Men    31  43  18
Women  26  44  11

In [47]:
# df.reset_index(inplace=True)
df.assign(div = lambda x: (x['D']/ x['E']))
df

C   D   E
sex              
Men    31  43  18
Women  26  44  11

In [48]:
print(df)

        C   D   E
sex              
Men    31  43  18
Women  26  44  11


### ***Conditional selection***

In [50]:
filling_data = np.random.randint(10,50, size = (2,3))
df = pd.DataFrame(filling_data, index=['A','B'], columns=['C','D','E'])
df


C   D   E
A  17  42  34
B  28  40  25

In [52]:
print('greater then 40\n', df > 40)


greater then 40
        C      D      E
A  False   True  False
B  False  False  False


In [53]:
# greater then (gt)
# less then (lt)
#greater then or equal to (ge)
#less then or equal to(le)
#equal to (eq)
#not equal to (ne)
print('less then 30\n', df < 30)


less then 30
       C      D      E
A  True  False  False
B  True  False   True


In [54]:
# return a row if the condition match 
df[df['E'] > 30]

C   D   E
A  17  42  34

### ***File input/output***

In [3]:
cs_df = pd.read_csv('data/ComputerSales.csv')
ex_df = pd.read_excel('data/Financial Sample.xlsx', 0)


In [7]:
cs_df.head(3)

Sale ID      Contact Sex  Age State Product ID Product Type  Sale Price  \
0        1  Paul Thomas   M   43    OH  M01-F0024      Desktop      479.99   
1        2  Margo Simms   F   37    WV  GT13-0024      Desktop     1249.99   
2        3    Sam Stine   M   26    PA      I3670      Desktop      649.99   

   Profit     Lead     Month  Year  
0  143.39  Website   January  2018  
1  230.89  Flyer 4   January  2018  
2  118.64  Website  February  2018

In [8]:
#convert this csv to excel with new backup file 
# cs_df.to_excel('ComputerSalesBU.xlsx')
# pd.read_excel('ComputerSalesBU.xlsx')

### ***Basics and Math***

In [9]:
cs_df.head(2)

Sale ID      Contact Sex  Age State Product ID Product Type  Sale Price  \
0        1  Paul Thomas   M   43    OH  M01-F0024      Desktop      479.99   
1        2  Margo Simms   F   37    WV  GT13-0024      Desktop     1249.99   

   Profit     Lead    Month  Year  
0  143.39  Website  January  2018  
1  230.89  Flyer 4  January  2018

In [10]:
cs_df.tail(2)

Sale ID       Contact Sex  Age State Product ID Product Type  Sale Price  \
37       38  Doug Johnson   M   51    PA    GA401IV       Laptop     1349.99   
38       39    Moe Eggert   M   35    PA      I3593       Laptop      399.99   

    Profit     Lead Month  Year  
37  180.34  Website   May  2020  
38   72.09  Website   May  2020

In [11]:
cs_df.index.array

<PandasArray>
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
 38]
Length: 39, dtype: int64

In [12]:
cs_df.to_numpy()

array([[1, 'Paul Thomas', 'M', 43, 'OH', 'M01-F0024', 'Desktop', 479.99,
        143.39, 'Website', 'January', 2018],
       [2, 'Margo Simms', 'F', 37, 'WV', 'GT13-0024', 'Desktop', 1249.99,
        230.89, 'Flyer 4', 'January', 2018],
       [3, 'Sam Stine', 'M', 26, 'PA', 'I3670', 'Desktop', 649.99,
        118.64, 'Website', 'February', 2018],
       [4, 'Moe Eggert', 'M', 35, 'PA', 'I3593', 'Laptop', 399.99, 72.09,
        'Website', 'March', 2018],
       [5, 'Jessica Elk', 'F', 55, 'PA', '15M-ED', 'Laptop', 699.99,
        98.09, 'Flyer 4', 'March', 2018],
       [6, 'Sally Struthers', 'F', 45, 'PA', 'GT13-0024', 'Desktop',
        1249.99, 230.89, 'Flyer 2', 'April', 2018],
       [7, 'Michelle Samms', 'F', 46, 'OH', 'GA401IV', 'Laptop', 1349.99,
        180.34, 'Email', 'May', 2018],
       [8, 'Mick Roberts', 'M', 23, 'OH', 'MY2J2LL', 'Tablet', 999.99,
        146.69, 'Website', 'July', 2018],
       [9, 'Ed Klondike', 'M', 52, 'OH', '81TC00', 'Laptop', 649.99,
        122.34

### ***Group data***

In [14]:
dicty = {
    'Store' : [1,2,1,2],
    'Flavor' : ['Choc', 'van','Straw','Choc'],
    'Sales' : [26,12,18,22]
}
gd_df = pd.DataFrame(dicty)

In [15]:
# 
by_store = gd_df.groupby('Store')

In [16]:
by_store.mean()

TypeError: Could not convert ChocStraw to numeric

### ***Handling missing data***

In [11]:
dicty = {
    'A' : [1,2,np.nan],
    'B' : [4,np.nan,np.nan],
    'C' : [7,8,9]
}
df = pd.DataFrame(dicty)

In [13]:
df
# for rows
# df.dropna()

#for column
df.dropna(axis=1)

#drop a row with atlest 2 nun values
df.dropna(thresh=2)

A    B  C
0  1.0  4.0  7
1  2.0  NaN  8

In [17]:
# fill with dta
df.fillna(value=0.0)
df.fillna(value=df['A'].mean())

# fill pervious vulae
df.fillna(method='ffill')

A    B  C
0  1.0  4.0  7
1  2.0  4.0  8
2  2.0  4.0  9

### ***Experimenting with data***

In [4]:
cs_df.head()

Sale ID      Contact Sex  Age State Product ID Product Type  Sale Price  \
0        1  Paul Thomas   M   43    OH  M01-F0024      Desktop      479.99   
1        2  Margo Simms   F   37    WV  GT13-0024      Desktop     1249.99   
2        3    Sam Stine   M   26    PA      I3670      Desktop      649.99   
3        4   Moe Eggert   M   35    PA      I3593       Laptop      399.99   
4        5  Jessica Elk   F   55    PA     15M-ED       Laptop      699.99   

   Profit     Lead     Month  Year  
0  143.39  Website   January  2018  
1  230.89  Flyer 4   January  2018  
2  118.64  Website  February  2018  
3   72.09  Website     March  2018  
4   98.09  Flyer 4     March  2018

In [5]:
cs_df.columns

Index(['Sale ID', 'Contact', 'Sex', 'Age', 'State', 'Product ID',
       'Product Type', 'Sale Price', 'Profit', 'Lead', 'Month', 'Year'],
      dtype='object')

In [6]:
cs_df['Profit'].mean()

139.97461538461542

In [9]:
cs_df[['Product ID','Profit']].max(axis=0)
cs_df[cs_df['State']=='WV']['State'].count()

4

In [10]:
len(cs_df[cs_df['Year']==2019].index)

14

In [11]:
cs_df['Product ID'].value_counts()

Product ID
GA401IV      6
M01-F0024    5
I3593        5
81TC00       5
GT13-0024    4
15M-ED       4
MY2J2LL      4
I3670        3
Q526FA       3
Name: count, dtype: int64

In [12]:
cs_df[cs_df['Product ID']=='M01-F0024']['Contact']

0     Paul Thomas
9      Phil Jones
20     Jason Case
29     Phil Jones
36     Jason Case
Name: Contact, dtype: object

In [16]:
cs_df[(cs_df['Lead']=='Website') & (cs_df['Profit']>150)]['Lead'].count()

2

In [17]:
cs_df['Profit'].apply(lambda cents: str(cents).split('.')[1]=='89').value_counts()

Profit
False    35
True      4
Name: count, dtype: int64