# **all in one** 

### ***numpy arrays: creating arrays***

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import random


In [ ]:
list_1 = [1,2,3,4,5]
np_arr_1 = np.array(list_1, dtype=np.int8)
np_arr_1

In [ ]:
list_1 = np.arange(1,10)
list_1

In [ ]:
list_1 = np.linspace(0,5,5)
list_1

In [ ]:
z_list = np.zeros((2,2))
z_list

In [ ]:
ran = np.random.randint(10,50, size=(2,2))
ran2 = np.random.randint(10,50,10)
ran2
disk = np.array(np.arange(1,10))
print(disk)

### ***Slicing and indexes***

In [ ]:
new_list = np.random.randint(1,50, size=(5,5))
new_list

In [ ]:
new_list[0,2] = 7

In [ ]:
new_list

In [ ]:
sub_mat = new_list[1:4, 1:4]
sub_mat

In [ ]:
np.take(sub_mat,[0,4,8] )

In [ ]:
np.put(sub_mat,[0,3,6], [10,10,10])

In [ ]:
sub_mat

In [ ]:
sub_mat[ : , : ]

In [ ]:
even = sub_mat[sub_mat%2==0]

In [ ]:
even

In [ ]:
less = sub_mat[sub_mat > 5]
less

In [ ]:
uni = np.unique(sub_mat)
uni

### ***Reshaping arrays***

In [ ]:
new_list


In [ ]:
sub_mat

In [ ]:
# reshape array just give you a copy of it not change the orignal array
new_list.reshape((1,25))

In [ ]:
new_list

In [ ]:
#resize change the orignal array
new_list.resize((1,25))

In [ ]:
new_list.transpose()
new_list

In [ ]:
new_list.resize((5,5))
new_list

In [ ]:
new_list.swapaxes(0,1)

In [ ]:
new_list.flatten()

In [ ]:
new_list.sort(axis=1)

new_list

### ***Stacking and splitting***

In [ ]:
ss_arr_1 = np.random.randint(10,size=(2,2))
print('ss_arr_1\n',ss_arr_1)
ss_arr_2 = np.random.randint(10,size=(2,2))
print('ss_arr_2\n',ss_arr_2)

print(np.vstack((ss_arr_2,ss_arr_1)))


### ***Copying***

In [ ]:
cp_arr_1 = np.random.randint(1,50, size=(5,5))
cp_arr_1

In [ ]:
sub_arr = cp_arr_1[1:4 , 1:4].copy()

In [ ]:
sub_arr

In [ ]:
sub_arr[0,0] = 3

In [ ]:
cp_arr_1

### ***Basic Math***

In [ ]:
arr_1 = random.randint(1,100, size=(7,7))


In [ ]:
arr_1

In [ ]:
arr_1.sum()

In [ ]:
#axis = 0 for column
#axis = 1 for row
arr_1.min(axis=1)

In [ ]:
#cumulative sum is adding all perivous values
arr_1.cumsum(axis=1)

In [ ]:
# For element (1 % 5) = 1.
# For element (2 % 6) = 2.
# For element (3 % 7) = 3.
# For element (4 % 8) = 4.
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])

np.remainder(arr_1,arr_2)

In [ ]:
# (1^5) = 1
# (2^6) = 64
# (3^7) = 2187
# (4^8) = 65536
np.power(arr_1,arr_2)

In [ ]:
np.sqrt(arr_1)

In [ ]:
np.absolute([-1,-2])

In [ ]:
np.log(arr_1)

In [ ]:
# gcd
np.gcd.reduce([9,12,15])

In [ ]:
np.lcm.reduce([9,12,15])

In [ ]:
np.floor([1.2,2.5])

In [ ]:
np.ceil([2.4,6.7])

### ***Reading from files***

In [13]:
import pandas as pd
from numpy import genfromtxt

In [14]:
ic_sales = pd.read_csv('ice_cream_sales.csv').to_numpy()

In [15]:
ic_sales

array([[ 37, 292],
       [ 40, 228],
       [ 49, 324],
       [ 61, 376],
       [ 72, 440],
       [ 79, 496],
       [ 83, 536],
       [ 81, 556],
       [ 75, 496],
       [ 64, 412],
       [ 53, 324],
       [ 40, 320]], dtype=int64)

In [16]:
ic_sales_2 = genfromtxt('ice_cream_sales.csv', delimiter=',')

### ***Statistics Function***

In [17]:
import numpy as np
sarr_1 = np.arange(1,6)


In [18]:
np.mean(sarr_1)

3.0

In [19]:
np.median(sarr_1)

3.0

In [20]:
np.std(sarr_1)

1.4142135623730951

In [21]:
np.var(sarr_1)

2.0

In [22]:
np.var([4,6,3,5,3])

1.3599999999999999

In [23]:
#nanmedian , nanmean
print(ic_sales)

[[ 37 292]
 [ 40 228]
 [ 49 324]
 [ 61 376]
 [ 72 440]
 [ 79 496]
 [ 83 536]
 [ 81 556]
 [ 75 496]
 [ 64 412]
 [ 53 324]
 [ 40 320]]


In [26]:
np.percentile(ic_sales, 50, axis=1)

array([164.5, 134. , 186.5, 218.5, 256. , 287.5, 309.5, 318.5, 285.5,
       238. , 188.5, 180. ])

In [27]:
np.corrcoef(ic_sales[:, 0],ic_sales[:,1])

array([[1.        , 0.96181329],
       [0.96181329, 1.        ]])

### ***Creating Formula***

In [ ]:
# Calculating Regression Line
# sigma(x-X)
tem_mean = np.mean(ic_sales[:,0])
sales_mean = np.mean(ic_sales[:,1])

numerator = np.sum(((ic_sales[:,0] - tem_mean) * (ic_sales[:,1] - sales_mean)))


### ***Linear Algebra Fucntion***

In [29]:
from numpy import linalg as LA


In [35]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[2,4],[6,9]])
print(arr_1)
print(arr_2)  

[[1 2]
 [3 4]]
[[2 4]
 [6 9]]


In [37]:
# martix multiplication with dot product 
#(1 * 2) + (2 * 6) = 14 [0,0]
#(1 * 4) + (2 * 9) = 22 [0,1]
#(3 * 2) + (4 * 6) = 30 [1,0]
#(3 * 4) + (4 * 9) = 12 + 36 = 48 [1,1]
np.dot(arr_1,arr_2)
# multi_dot use multiple arrays
LA.multi_dot([arr_1,arr_2])

array([[14, 22],
       [30, 48]])

In [39]:
# inner product
# (1 * 2) + (2 * 4) = 10 [0,0]
# (1 * 4) + (2 * 9) = 24 [0,1]
# (3 * 2) + (4 * 6) = 22 [1,0]
# (3 * 4) + (4 * 9) = 54 [1,1]
np.inner(arr_1,arr_2)


array([[10, 24],
       [22, 54]])

### ***Saving and Loading Numpy Objects***

In [41]:
arr = np.array([[1,2],[3,4]])
np.save('randarray',arr)
new_arr = np.load('randarray.npy')
new_arr

array([[1, 2],
       [3, 4]])

In [42]:
np.savetxt('randcsv.csv',arr)
new_arr = np.loadtxt('randcsv.csv')
new_arr

array([[1., 2.],
       [3., 4.]])

### ***Financial Functions***

In [43]:
import numpy_financial as npf


In [44]:
# feature value of 400 dollor investment every single mounth with an anual rate of return of 8% see how much monay after 10 months  
npf.fv(.08/12, 10*12, -400,-400)

74066.27016650053